name: CI

on:
  push:
    branches:
      - master
      - 'dependabot/**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install latest npm
        run: npm install --global npm@latest
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
